export const projectsList = [
  {
    name: "NailStyle",
    route: "/projects/nailstyle",
    image: "",
    description:
      "Nail Salon website application built on the MERN (MongoDB, Express, React, Node.js) stack to learn React and flesh out full stack skillset. Features a simple RESTful API implementation. The app has a terminal for admins to manage customers, employees and appointments, as well as an appointment page for customers.",
    type: "Personal",
    year: "2021",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "React.js",
      "Node.js",
      "Express",
      "Axios",
      "MongoDB",
      "Heroku",
      "Netlify",
    ],
    github: "https://github.com/Shewng/NailStyle",
    external: "https://hxnails.ca",
  },
  {
    name: "MENJI.",
    route: "/projects/menji",
    image: "",
    description:
      "Final project for my Database Management course, mimicking an online eCommerce clothing store. Features a simple RESTful API implementation. Clients can log into their account, browse products, add/remove them from their cart, checkout with personal information and review their orders.",
    type: "University",
    year: "2021",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "Node.js",
      "Express",
      "Axios",
      "MongoDB",
      "Mongoose",
    ],
    github: "https://github.com/Shewng/Menji",
    external: "",
  },
  {
    name: "Personal Portfolio",
    route: "/projects/portfolio",
    image: "",
    description:
      "This website was originally envisioned using the JAMstack development architecture, but I decided to keep things simpler and reserve it for another project. I have used plain React, SASS and Javascript for my first website iteration.",
    type: "Personal",
    year: "2021",
    technologies: ["HTML", "SASS", "JavaScript", "React", "Next.js", "Vercel"],
    github: "https://github.com/Shewng/personal-portfolio",
    external: "",
  },
  {
    name: "MakeApp",
    route: "/projects/makeapp",
    image: "",
    description:
      "Final project for my iOS development course, mimicking a social media application based on creating makeupp routines. Built on SwiftUI using Firebase’s Cloud Firestore to manage backend infrastructure.",
    type: "University",
    year: "2020",
    technologies: ["Swift", "Firebase"],
    github: "https://github.com/Shewng/makeup",
    external: "",
  },
  {
    name: "Plants Vs Zombies Clone",
    route: "/projects/pvz",
    image: "",
    description:
      "Final project for my Introductory Computer Science course, mimicking the famous Tower Defense game Plants Vs Zombies. I built this project with Object-Orientated principles in mind, utilizing Java’s class structure to create the plants and zombies. With JavaFX’s Scene Builder, I was able to program a game engine that tracked certain states, swaping between different displays when necessary.",
    type: "University",
    year: "2018",
    technologies: ["Java", "JavaFX"],
    github: "https://github.com/Shewng/pvz-ms-remake",
    external: "",
  },
  {
    name: "Laser Unlock",
    route: "/projects/laserunlock",
    image: "",
    description:
      "Phone application that re-envisions our phone-unlock methods from the traditional slide-to-unlock and pin/password. Using Android Studio’s sensor framework, I created minigame that mimics a cat trying to catch a laser. In order to unlock your phone, the cat must catch the laser 3 times in the correct positions.",
    type: "University",
    year: "2020",
    technologies: ["Java", "Android Studio"],
    github: "https://github.com/Shewng/Cat-and-Laser",
    external: "",
  },
  {
    name: "Minesweeper",
    route: "/projects/minesweeper",
    mage: "",
    description:
      "Final project for my Web-Based systems course, mimicking the popular browser game Minesweeper. Built on Javascript and JQuery to learn about front-end development and responsive design. ",
    type: "University",
    year: "2020",
    technologies: ["HTML", "CSS", "JavaScript", "jQuery"],
    github: "",
    external: "",
  },
  {
    name: "SmartSpace",
    route: "/projects/smartspace",
    image: "",
    description: "",
    type: "University",
    year: "2019",
    technologies: ["Adobe XD"],
    github: "",
    external:
      "https://xd.adobe.com/view/367c853f-9e22-4e1e-6688-2350bbd28618-404d/?fullscreen&hints=off",
  },
  {
    name: "ChaiSweetBakery",
    route: "/projects/chaisweetbakery",
    image: "",
    description:
      "Work-in-progress website built on React for my sister’s small local business. She needed her own site in order to sell, promote and showcase her business in a more professional manner. Informed by her suggestions and other user feedback, I designed and developed the site with the intention of a lighthearted, jovial (comforting, playful, spirited) aesthetic.",
    type: "Personal",
    year: "2021",
    technologies: [
      "HTML",
      "SCSS",
      "JavaScript",
      "React",
      "Docker",
      "Next.js",
      "Vercel",
    ],
    github: "https://github.com/Shewng/ChaiSweetBakery",
    external: "",
  },
];
