export const projectsList = [
  {
    name: "NailStyle",
    route: "/projects/nailstyle",
    previewImg: "/../public/test.png",
    description:
      "Nail Salon website application built on the MERN stack (MongoDB, Express, React, Node.js) to learn React and flesh out full stack skillset. Features a simple RESTful API implementation. The app has a terminal for admins to manage customers, employees and appointments, as well as an appointment page for customers.",
    longDescription:
      "Nail Salon website application built on the MERN stack (MongoDB, Express, React, Node.js) to learn React and further flesh out full stack skillset." +
      "\n\nI worked with a friend to revamp a local business’s nail salon website given a list of user requirements, issues to resolve and optimizations to add. We used Figma to build from the ground up, designing prototypes and wireframes to move forward iteratively. The intention was to develop good UX/UI habits to understand our problems from the client’s POV,  ensuring a smooth implementation" +
      "\n\nNailStyle has an admin terminal for the management of customers, employees and appointments, as well as a page for customers to book appointments. The app features RESTful API architecture, JSON Web Token authentication (for admins) and responsive design for desktop and mobile devices.",
    type: "Personal",
    year: "2021",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "React.js",
      "Node.js",
      "Express",
      "Axios",
      "MongoDB",
      "Heroku",
      "Netlify",
    ],
    images: [
      "/../public/nailstyle/nailstyle1.png",
      "/../public/nailstyle/nailstyle2.png",
      "/../public/nailstyle/nailstyle3.png",
    ],
    github: "https://github.com/Shewng/NailStyle",
    external: "https://hxnails.ca",
  },
  {
    name: "MENJI.",
    route: "/projects/menji",
    previewImg: "/../public/nightcity.gif",
    description:
      "Final project for my Database Management course, mimicking an online eCommerce clothing store. Features a simple RESTful API implementation. Clients can log into their account, browse products, add/remove them from their cart, checkout with personal information and review their orders.",
    longDescription:
      "Partnered final project for my Database Management course, mimicking an online eCommerce clothing store. We were tasked with creating a problem and design process, building the entire project through a near full-stack implementation." +
      "\n\nMenji. utilizes a simple REST implementation alongside MongoDB’s NoSQL database to add, remove and load the products and registered users. HTTP web cookies are used for the login/register process of customers and admins. We were tasked to include a step-by-step procedure of the project, with an emphasis on mapping how our data flowed through numerous interactions. This was achieved by creating relationship model diagrams and documenting API endpoints via the Postman API platform." +
      "\n\nUsers can browse the merchandise, add/remove them from their cart, checkout the cart with their personal information and review their orders. Admins can view all registered customers, manage the store’s inventory and track orders placed by customers.",
    type: "University",
    year: "2021",
    technologies: [
      "HTML",
      "CSS",
      "JavaScript",
      "Node.js",
      "Express",
      "Axios",
      "MongoDB",
      "Mongoose",
    ],
    images: [
      "/../public/menji/menji1.png",
      "/../public/menji/menji2.png",
      "/../public/menji/menji3.png",
    ],
    github: "https://github.com/Shewng/Menji",
    external: "",
  },
  {
    name: "Personal Portfolio",
    route: "/projects/portfolio",
    previewImg: "/../public/nightcity.gif",
    description:
      "My first website iteration, created through Next js and SCSS. My design inspiration was through a combination of minimalism and an avant-garde edge. I hope to create a modular/scalable version in the future, allowing me to fully transform the site into an autobiography of myself.",
    longDescription: "",
    type: "Personal",
    year: "2021",
    technologies: ["HTML", "SASS", "JavaScript", "React", "Next.js", "Vercel"],
    images: [
      "/../public/nightcity.gif",
      "/../public/nightcity.gif",
      "/../public/nightcity.gif",
    ],
    github: "https://github.com/Shewng/personal-portfolio",
    external: "https://shwong.me",
  },
  {
    name: "MakeApp",
    route: "/projects/makeapp",
    previewImg: "/../public/nightcity.gif",
    description:
      "Final project for my iOS development course, mimicking a social media application based on creating makeupp routines. Built on SwiftUI using Firebase’s Cloud Firestore to manage backend infrastructure.",
    longDescription: "",
    type: "University",
    year: "2020",
    technologies: ["Swift", "Firebase"],
    images: ["", "", ""],
    github: "https://github.com/Shewng/makeup",
    external: "",
  },
  {
    name: "Plants Vs Zombies Clone",
    route: "/projects/pvz",
    previewImg: "/../public/nightcity.gif",
    description:
      "Final project for my Introductory Computer Science course, mimicking the famous Tower Defense game Plants Vs Zombies. I built this project with Object-Orientated principles in mind, utilizing Java’s class structure to create the plants and zombies. With JavaFX’s Scene Builder, I was able to program a game engine that tracked certain states, swaping between different displays when necessary.",
    longDescription: "",
    type: "University",
    year: "2018",
    technologies: ["Java", "JavaFX"],
    images: ["", "", ""],
    github: "https://github.com/Shewng/pvz-ms-remake",
    external: "",
  },
  {
    name: "Laser Unlock",
    route: "/projects/laserunlock",
    previewImg: "/../public/nightcity.gif",
    description:
      "Phone application that re-envisions our phone-unlock methods from the traditional slide-to-unlock and pin/password. Using Android Studio’s sensor framework, I created minigame that mimics a cat trying to catch a laser. In order to unlock your phone, the cat must catch the laser 3 times in the correct positions.",
    longDescription: "",
    type: "University",
    year: "2020",
    technologies: ["Java", "Android Studio"],
    images: [
      "/../public/smartspace/smartspace1.png",
      "/../public/smartspace/smartspace2.png",
      "/../public/smartspace/smartspace3.png",
    ],
    github: "https://github.com/Shewng/Cat-and-Laser",
    external: "",
  },
  /**{
    name: "Minesweeper",
    route: "/projects/minesweeper",
    previewImg: "/../public/nightcity.gif",
    description:
      "Final project for my Web-Based systems course, mimicking the popular browser game Minesweeper. Built on Javascript and JQuery to learn about front-end development and responsive design. ",
    longDescription: "",
    type: "University",
    year: "2020",
    technologies: ["HTML", "CSS", "JavaScript", "jQuery"],
    images: ["", "", ""],
    github: "",
    external: "",
  },*/
  {
    name: "SmartSpace",
    route: "/projects/smartspace",
    previewImg: "/../public/nightcity.gif",
    description: "",
    longDescription: "",
    type: "University",
    year: "2019",
    technologies: ["Adobe XD"],
    images: [
      "/../public/smartspace/smartspace1.png",
      "/../public/smartspace/smartspace2.png",
      "/../public/smartspace/smartspace3.png",
    ],
    github: "",
    external:
      "https://xd.adobe.com/view/367c853f-9e22-4e1e-6688-2350bbd28618-404d/?fullscreen&hints=off",
  },
  {
    name: "ChaiSweetBakery",
    route: "/projects/chaisweetbakery",
    previewImg: "/../public/nightcity.gif",
    description:
      "Work-in-progress website built on React for my sister’s small local business. As she only used social media, I offered to create a more professional showcase of her business via a website to better sell, promote and track her creations.  Informed by suggestions and user feedback, I designed and developed the site with the intention of a lighthearted, jovial (comforting, playful, spirited) aesthetic.",
    longDescription: "" + "" + "",
    type: "Personal",
    year: "2021",
    technologies: [
      "HTML",
      "SCSS",
      "JavaScript",
      "React",
      "Docker",
      "Next.js",
      "Vercel",
    ],
    images: ["", "", ""],
    github: "https://github.com/Shewng/ChaiSweetBakery",
    external: "",
  },
];
